/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_iworks_jni_math_JNIMath */

#ifndef _Included_de_iworks_jni_math_JNIMath
#define _Included_de_iworks_jni_math_JNIMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_iworks_jni_math_JNIMath
 * Method:    abs
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_de_iworks_jni_math_JNIMath_abs
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     de_iworks_jni_math_JNIMath
 * Method:    sqrt
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_de_iworks_jni_math_JNIMath_sqrt__D
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     de_iworks_jni_math_JNIMath
 * Method:    sqrt
 * Signature: (DDI)D
 */
JNIEXPORT jdouble JNICALL Java_de_iworks_jni_math_JNIMath_sqrt__DDI
  (JNIEnv *, jclass, jdouble, jdouble, jint);

/*
 * Class:     de_iworks_jni_math_JNIMath
 * Method:    sqrt
 * Signature: (DDII)D
 */
JNIEXPORT jdouble JNICALL Java_de_iworks_jni_math_JNIMath_sqrt__DDII
  (JNIEnv *, jclass, jdouble, jdouble, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
